spring.application.name=Route Optimizer
server.servlet.context-path=/CourierSync/api
server.port=${PORT:8080}

# Database Configuration (usar variables de entorno locales o GitHub Secrets)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}